# name|wireguard_ip|role
princess.kori.cat|10.10.0.2|webserver + ns1
bumblezone.kori.cat|10.10.0.3|NekoMusic DB backup + ns2
nekomail.kori.cat|10.10.0.4|email + ns3
aisaka.kori.cat|10.10.0.6|nekobot
laika.kori.cat|10.10.0.7|Coordinator B / backup-gra
falfa.kori.cat|10.10.0.8|Coordinator A / backup-bhs
unknown1.kori.cat|10.10.0.9|TBD
unknown2.kori.cat|10.10.0.10|TBD
unknown3.kori.cat|10.10.0.11|TBD
momo.nekomusic.ca|10.10.0.50|NekoMusic DB primary
sylphiette.nekomusic.ca|10.10.0.51|Master 1
yachiru.nekomusic.ca|10.10.0.52|Web-A active
yuno.nekomusic.ca|10.10.0.53|Slave 1
hinata.nekomusic.ca|10.10.0.54|Slave 2
linia.nekomusic.ca|10.10.0.55|Master 2
roxy.nekomusic.ca|10.10.0.56|Web-B standby
rokari.nekomusic.ca|10.10.0.57|Slave 3
minitona.nekomusic.ca|10.10.0.58|Slave 4
